# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 371)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 351))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #232526, stop:1 #414345);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(270, 30, 231, 181))
        self.label.setStyleSheet("background-color: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo/asli.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(160, 240, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.home_btn_start = QtWidgets.QPushButton(self.widget)
        self.home_btn_start.setGeometry(QtCore.QRect(670, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.home_btn_start.setFont(font)
        self.home_btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_start.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.home_btn_start.setObjectName("home_btn_start")
        self.home_btn_author = QtWidgets.QPushButton(self.widget)
        self.home_btn_author.setGeometry(QtCore.QRect(10, 290, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.home_btn_author.setFont(font)
        self.home_btn_author.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_author.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.home_btn_author.setObjectName("home_btn_author")
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setGeometry(QtCore.QRect(740, 10, 31, 21))
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(211, 0, 0);\n"
"")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(260, 290, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Welcome to YouTube Downloader"))
        self.home_btn_start.setText(_translate("MainWindow", "Start"))
        self.home_btn_author.setText(_translate("MainWindow", "Author"))
        self.label_3.setText(_translate("MainWindow", "Sajjad fani"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
