# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowYouTube(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 391)
        MainWindow.setMinimumSize(QtCore.QSize(799, 391))
        MainWindow.setMaximumSize(QtCore.QSize(799, 391))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 371))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #232526, stop:1 #414345);\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.btn_exit = QtWidgets.QPushButton(self.widget)
        self.btn_exit.setGeometry(QtCore.QRect(740, 10, 31, 21))
        self.btn_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_exit.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(211, 0, 0);\n"
"")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_mini = QtWidgets.QPushButton(self.widget)
        self.btn_mini.setGeometry(QtCore.QRect(700, 10, 31, 21))
        self.btn_mini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mini.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(171, 171, 0);")
        self.btn_mini.setText("")
        self.btn_mini.setObjectName("btn_mini")
        self.mainpage = QtWidgets.QStackedWidget(self.widget)
        self.mainpage.setGeometry(QtCore.QRect(0, 60, 781, 311))
        self.mainpage.setStyleSheet("")
        self.mainpage.setObjectName("mainpage")
        self.youtube_url = QtWidgets.QWidget()
        self.youtube_url.setObjectName("youtube_url")
        self.url_lineEdit_link = QtWidgets.QLineEdit(self.youtube_url)
        self.url_lineEdit_link.setGeometry(QtCore.QRect(80, 10, 641, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.url_lineEdit_link.setFont(font)
        self.url_lineEdit_link.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.url_lineEdit_link.setObjectName("url_lineEdit_link")
        self.url_label_link = QtWidgets.QLabel(self.youtube_url)
        self.url_label_link.setGeometry(QtCore.QRect(19, 12, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.url_label_link.setFont(font)
        self.url_label_link.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_link.setObjectName("url_label_link")
        self.url_frame_option = QtWidgets.QFrame(self.youtube_url)
        self.url_frame_option.setGeometry(QtCore.QRect(0, 50, 781, 261))
        self.url_frame_option.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_frame_option.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_frame_option.setObjectName("url_frame_option")
        self.url_pict_label = QtWidgets.QLabel(self.url_frame_option)
        self.url_pict_label.setGeometry(QtCore.QRect(26, 10, 271, 241))
        self.url_pict_label.setStyleSheet("border-radius:20px;")
        self.url_pict_label.setText("")
        self.url_pict_label.setObjectName("url_pict_label")
        self.url_label_title = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_title.setGeometry(QtCore.QRect(320, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.url_label_title.setFont(font)
        self.url_label_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_title.setObjectName("url_label_title")
        self.url_label_view = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_view.setGeometry(QtCore.QRect(320, 70, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_view.setFont(font)
        self.url_label_view.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_view.setObjectName("url_label_view")
        self.url_label_time = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_time.setGeometry(QtCore.QRect(320, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_time.setFont(font)
        self.url_label_time.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_time.setObjectName("url_label_time")
        self.url_label_rating = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_rating.setGeometry(QtCore.QRect(320, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_rating.setFont(font)
        self.url_label_rating.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_rating.setObjectName("url_label_rating")
        self.url_label_title_Ent = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_title_Ent.setGeometry(QtCore.QRect(378, 23, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_title_Ent.setFont(font)
        self.url_label_title_Ent.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.url_label_title_Ent.setText("")
        self.url_label_title_Ent.setObjectName("url_label_title_Ent")
        self.url_label_view_Ent = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_view_Ent.setGeometry(QtCore.QRect(380, 68, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_view_Ent.setFont(font)
        self.url_label_view_Ent.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_view_Ent.setText("")
        self.url_label_view_Ent.setObjectName("url_label_view_Ent")
        self.url_label_time_Ent = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_time_Ent.setGeometry(QtCore.QRect(378, 118, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_time_Ent.setFont(font)
        self.url_label_time_Ent.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_time_Ent.setText("")
        self.url_label_time_Ent.setObjectName("url_label_time_Ent")
        self.url_label_rating_Ent = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_rating_Ent.setGeometry(QtCore.QRect(382, 168, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_rating_Ent.setFont(font)
        self.url_label_rating_Ent.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_rating_Ent.setText("")
        self.url_label_rating_Ent.setObjectName("url_label_rating_Ent")
        self.url_btn_next = QtWidgets.QPushButton(self.url_frame_option)
        self.url_btn_next.setGeometry(QtCore.QRect(660, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_btn_next.setFont(font)
        self.url_btn_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.url_btn_next.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"}\n"
"")
        self.url_btn_next.setObjectName("url_btn_next")
        self.url_label_waiting = QtWidgets.QLabel(self.url_frame_option)
        self.url_label_waiting.setGeometry(QtCore.QRect(420, 218, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.url_label_waiting.setFont(font)
        self.url_label_waiting.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_waiting.setObjectName("url_label_waiting")
        self.url_btn_submit = QtWidgets.QPushButton(self.youtube_url)
        self.url_btn_submit.setGeometry(QtCore.QRect(730, 10, 41, 41))
        self.url_btn_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.url_btn_submit.setStyleSheet("\n"
"QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"}\n"
"")
        self.url_btn_submit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/true.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.url_btn_submit.setIcon(icon)
        self.url_btn_submit.setIconSize(QtCore.QSize(20, 20))
        self.url_btn_submit.setObjectName("url_btn_submit")
        self.mainpage.addWidget(self.youtube_url)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.setting_label_pict = QtWidgets.QLabel(self.setting)
        self.setting_label_pict.setGeometry(QtCore.QRect(20, -2, 271, 241))
        self.setting_label_pict.setStyleSheet("border-radius:20px;")
        self.setting_label_pict.setText("")
        self.setting_label_pict.setObjectName("setting_label_pict")
        self.setting_label_res = QtWidgets.QLabel(self.setting)
        self.setting_label_res.setGeometry(QtCore.QRect(307, 32, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_label_res.setFont(font)
        self.setting_label_res.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.setting_label_res.setObjectName("setting_label_res")
        self.setting_comboBox_res = QtWidgets.QComboBox(self.setting)
        self.setting_comboBox_res.setGeometry(QtCore.QRect(408, 38, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_comboBox_res.setFont(font)
        self.setting_comboBox_res.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px;\n"
"")
        self.setting_comboBox_res.setObjectName("setting_comboBox_res")
        self.setting_label_location = QtWidgets.QLabel(self.setting)
        self.setting_label_location.setGeometry(QtCore.QRect(307, 133, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_label_location.setFont(font)
        self.setting_label_location.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.setting_label_location.setObjectName("setting_label_location")
        self.setting_lineEdit_browse = QtWidgets.QLineEdit(self.setting)
        self.setting_lineEdit_browse.setGeometry(QtCore.QRect(397, 135, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_lineEdit_browse.setFont(font)
        self.setting_lineEdit_browse.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px;\n"
"")
        self.setting_lineEdit_browse.setObjectName("setting_lineEdit_browse")
        self.setting_btn_browse = QtWidgets.QPushButton(self.setting)
        self.setting_btn_browse.setGeometry(QtCore.QRect(678, 135, 81, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_btn_browse.setFont(font)
        self.setting_btn_browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn_browse.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(130, 130, 130);")
        self.setting_btn_browse.setObjectName("setting_btn_browse")
        self.setting_btn_download = QtWidgets.QPushButton(self.setting)
        self.setting_btn_download.setGeometry(QtCore.QRect(620, 254, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_btn_download.setFont(font)
        self.setting_btn_download.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn_download.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.setting_btn_download.setObjectName("setting_btn_download")
        self.setting_btn_back = QtWidgets.QPushButton(self.setting)
        self.setting_btn_back.setGeometry(QtCore.QRect(468, 254, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_btn_back.setFont(font)
        self.setting_btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn_back.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.setting_btn_back.setObjectName("setting_btn_back")
        self.setting_frame_warning = QtWidgets.QFrame(self.setting)
        self.setting_frame_warning.setGeometry(QtCore.QRect(310, 197, 311, 31))
        self.setting_frame_warning.setStyleSheet("background-color: none;")
        self.setting_frame_warning.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setting_frame_warning.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setting_frame_warning.setObjectName("setting_frame_warning")
        self.label_4 = QtWidgets.QLabel(self.setting_frame_warning)
        self.label_4.setGeometry(QtCore.QRect(0, -6, 41, 41))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("photo/outline_warning_white_24dp.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.setting_label_warning = QtWidgets.QLabel(self.setting_frame_warning)
        self.setting_label_warning.setGeometry(QtCore.QRect(40, 0, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setItalic(True)
        self.setting_label_warning.setFont(font)
        self.setting_label_warning.setStyleSheet("background-color: none;\n"
"color: rgb(216, 0, 0);")
        self.setting_label_warning.setObjectName("setting_label_warning")
        self.setting_label_location_2 = QtWidgets.QLabel(self.setting)
        self.setting_label_location_2.setGeometry(QtCore.QRect(20, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_label_location_2.setFont(font)
        self.setting_label_location_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.setting_label_location_2.setObjectName("setting_label_location_2")
        self.setting_label_size = QtWidgets.QLabel(self.setting)
        self.setting_label_size.setGeometry(QtCore.QRect(160, 250, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.setting_label_size.setFont(font)
        self.setting_label_size.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.setting_label_size.setText("")
        self.setting_label_size.setObjectName("setting_label_size")
        self.mainpage.addWidget(self.setting)
        self.download = QtWidgets.QWidget()
        self.download.setObjectName("download")
        self.download_progressBar = QtWidgets.QProgressBar(self.download)
        self.download_progressBar.setGeometry(QtCore.QRect(70, 60, 651, 31))
        self.download_progressBar.setStyleSheet("QProgressBar::chunk{\n"
"border-radius:5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29, stop:0.5 #302b63 ,stop:1 #24243e);\n"
"}\n"
"QProgressBar{\n"
"background-color:#CCCCFF;\n"
"color:#000000;\n"
"border-style:none;\n"
"border-radius:5px;\n"
"text-align:center;\n"
"height:50px;\n"
"}")
        self.download_progressBar.setProperty("value", 24)
        self.download_progressBar.setObjectName("download_progressBar")
        self.download_label_underProcess = QtWidgets.QLabel(self.download)
        self.download_label_underProcess.setGeometry(QtCore.QRect(200, 120, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.download_label_underProcess.setFont(font)
        self.download_label_underProcess.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.download_label_underProcess.setAlignment(QtCore.Qt.AlignCenter)
        self.download_label_underProcess.setObjectName("download_label_underProcess")
        self.download_frame_btns = QtWidgets.QFrame(self.download)
        self.download_frame_btns.setGeometry(QtCore.QRect(20, 220, 741, 80))
        self.download_frame_btns.setStyleSheet("background-color: none;")
        self.download_frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.download_frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.download_frame_btns.setObjectName("download_frame_btns")
        self.download_btn_backLink = QtWidgets.QPushButton(self.download_frame_btns)
        self.download_btn_backLink.setGeometry(QtCore.QRect(210, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.download_btn_backLink.setFont(font)
        self.download_btn_backLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn_backLink.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.download_btn_backLink.setObjectName("download_btn_backLink")
        self.download_btn_openFile = QtWidgets.QPushButton(self.download_frame_btns)
        self.download_btn_openFile.setGeometry(QtCore.QRect(390, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.download_btn_openFile.setFont(font)
        self.download_btn_openFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn_openFile.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.download_btn_openFile.setObjectName("download_btn_openFile")
        self.download_btn_open = QtWidgets.QPushButton(self.download_frame_btns)
        self.download_btn_open.setGeometry(QtCore.QRect(570, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.download_btn_open.setFont(font)
        self.download_btn_open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn_open.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.download_btn_open.setObjectName("download_btn_open")
        self.download_btn_backHome = QtWidgets.QPushButton(self.download_frame_btns)
        self.download_btn_backHome.setGeometry(QtCore.QRect(40, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.download_btn_backHome.setFont(font)
        self.download_btn_backHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn_backHome.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0f0c29,stop:0.5 #302b63,stop:1 #24243e);\n"
"border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #283c86, stop:1 #45a247);\n"
"border-radius:8px;\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.download_btn_backHome.setObjectName("download_btn_backHome")
        self.mainpage.addWidget(self.download)
        self.url_frame_setting = QtWidgets.QFrame(self.widget)
        self.url_frame_setting.setGeometry(QtCore.QRect(320, 10, 121, 41))
        self.url_frame_setting.setStyleSheet("")
        self.url_frame_setting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_frame_setting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_frame_setting.setObjectName("url_frame_setting")
        self.url_label_setting_top = QtWidgets.QLabel(self.url_frame_setting)
        self.url_label_setting_top.setGeometry(QtCore.QRect(38, 3, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.url_label_setting_top.setFont(font)
        self.url_label_setting_top.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_setting_top.setAlignment(QtCore.Qt.AlignCenter)
        self.url_label_setting_top.setObjectName("url_label_setting_top")
        self.label_3 = QtWidgets.QLabel(self.url_frame_setting)
        self.label_3.setGeometry(QtCore.QRect(3, 4, 31, 31))
        self.label_3.setStyleSheet("background-color: none;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("photo/outline_settings_white_24dp.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.url_frame_youtube = QtWidgets.QFrame(self.widget)
        self.url_frame_youtube.setGeometry(QtCore.QRect(56, 10, 151, 41))
        self.url_frame_youtube.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_frame_youtube.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_frame_youtube.setObjectName("url_frame_youtube")
        self.label = QtWidgets.QLabel(self.url_frame_youtube)
        self.label.setGeometry(QtCore.QRect(2, 5, 31, 31))
        self.label.setStyleSheet("background-color: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photo/outline_link_white_24dp.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.url_label_youtube_top = QtWidgets.QLabel(self.url_frame_youtube)
        self.url_label_youtube_top.setGeometry(QtCore.QRect(39, 4, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.url_label_youtube_top.setFont(font)
        self.url_label_youtube_top.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_youtube_top.setObjectName("url_label_youtube_top")
        self.url_frame_download = QtWidgets.QFrame(self.widget)
        self.url_frame_download.setGeometry(QtCore.QRect(555, 10, 131, 41))
        self.url_frame_download.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_frame_download.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_frame_download.setObjectName("url_frame_download")
        self.label_5 = QtWidgets.QLabel(self.url_frame_download)
        self.label_5.setGeometry(QtCore.QRect(5, 5, 31, 31))
        self.label_5.setStyleSheet("background-color: none;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("photo/outline_file_download_white_24dp.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.url_label_download_top = QtWidgets.QLabel(self.url_frame_download)
        self.url_label_download_top.setGeometry(QtCore.QRect(40, 4, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.url_label_download_top.setFont(font)
        self.url_label_download_top.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.url_label_download_top.setObjectName("url_label_download_top")
        self.url_line1 = QtWidgets.QFrame(self.widget)
        self.url_line1.setGeometry(QtCore.QRect(216, 20, 101, 21))
        self.url_line1.setStyleSheet("background-color: none;")
        self.url_line1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_line1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_line1.setObjectName("url_line1")
        self.label_8 = QtWidgets.QLabel(self.url_line1)
        self.label_8.setGeometry(QtCore.QRect(-4, -5, 41, 31))
        self.label_8.setStyleSheet("background-color: none;")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.url_line1)
        self.label_9.setGeometry(QtCore.QRect(31, -5, 31, 31))
        self.label_9.setStyleSheet("background-color: none;")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.url_line1)
        self.label_10.setGeometry(QtCore.QRect(60, 0, 31, 21))
        self.label_10.setStyleSheet("background-color: none;")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.url_line2 = QtWidgets.QFrame(self.widget)
        self.url_line2.setGeometry(QtCore.QRect(450, 20, 101, 21))
        self.url_line2.setStyleSheet("background-color: none;")
        self.url_line2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.url_line2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.url_line2.setObjectName("url_line2")
        self.label_7 = QtWidgets.QLabel(self.url_line2)
        self.label_7.setGeometry(QtCore.QRect(-2, -5, 31, 31))
        self.label_7.setStyleSheet("background-color: none;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.url_line2)
        self.label_11.setGeometry(QtCore.QRect(29, 0, 31, 21))
        self.label_11.setStyleSheet("background-color: none;")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.url_line2)
        self.label_12.setGeometry(QtCore.QRect(60, -5, 31, 31))
        self.label_12.setStyleSheet("background-color: none;")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("photo/outline_horizontal_rule_white_48dp.png"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainpage.setCurrentIndex(1)
        self.btn_exit.clicked.connect(MainWindow.close)
        self.btn_mini.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url_label_link.setText(_translate("MainWindow", "Link:"))
        self.url_label_title.setText(_translate("MainWindow", "Title:"))
        self.url_label_view.setText(_translate("MainWindow", "views:"))
        self.url_label_time.setText(_translate("MainWindow", "Time:"))
        self.url_label_rating.setText(_translate("MainWindow", "rating:"))
        self.url_btn_next.setText(_translate("MainWindow", "Next"))
        self.url_label_waiting.setText(_translate("MainWindow", "Please wait ..."))
        self.setting_label_res.setText(_translate("MainWindow", "Resolation:"))
        self.setting_label_location.setText(_translate("MainWindow", "Location:"))
        self.setting_btn_browse.setText(_translate("MainWindow", "Browse"))
        self.setting_btn_download.setText(_translate("MainWindow", "Download"))
        self.setting_btn_back.setText(_translate("MainWindow", "Back"))
        self.setting_label_warning.setText(_translate("MainWindow", "You should choose a location."))
        self.setting_label_location_2.setText(_translate("MainWindow", "Download size :"))
        self.download_label_underProcess.setText(_translate("MainWindow", "Downloading..."))
        self.download_btn_backLink.setText(_translate("MainWindow", "First page"))
        self.download_btn_openFile.setText(_translate("MainWindow", "Go file location"))
        self.download_btn_open.setText(_translate("MainWindow", "Open"))
        self.download_btn_backHome.setText(_translate("MainWindow", "Home page"))
        self.url_label_setting_top.setText(_translate("MainWindow", "Setting"))
        self.url_label_youtube_top.setText(_translate("MainWindow", "YouTube URL"))
        self.url_label_download_top.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
